set board(0) "xxxx                                                            "
set board(1) "oooo                                                            "
set board(2) "    xxxx                                                        "
set board(3) "    oooo                                                        "
set board(4) "        xxxx                                                    "
set board(5) "        oooo                                                    "
set board(6) "            xxxx                                                "
set board(7) "            oooo                                                "
set board(8) "                xxxx                                            "
set board(9) "                oooo                                            "
set board(10) "                    xxxx                                        "
set board(11) "                    oooo                                        "
set board(12) "                        xxxx                                    "
set board(13) "                        oooo                                    "
set board(14) "                            xxxx                                "
set board(15) "                            oooo                                "
set board(16) "                                xxxx                            "
set board(17) "                                oooo                            "
set board(18) "                                    xxxx                        "
set board(19) "                                    oooo                        "
set board(20) "                                        xxxx                    "
set board(21) "                                        oooo                    "
set board(22) "                                            xxxx                "
set board(23) "                                            oooo                "
set board(24) "                                                xxxx            "
set board(25) "                                                oooo            "
set board(26) "                                                    xxxx        "
set board(27) "                                                    oooo        "
set board(28) "                                                        xxxx    "
set board(29) "                                                        oooo    "
set board(30) "                                                            xxxx"
set board(31) "                                                            oooo"
set board(32) "x   x   x   x                                                   "
set board(33) "o   o   o   o                                                   "
set board(34) " x   x   x   x                                                  "
set board(35) " o   o   o   o                                                  "
set board(36) "  x   x   x   x                                                 "
set board(37) "  o   o   o   o                                                 "
set board(38) "   x   x   x   x                                                "
set board(39) "   o   o   o   o                                                "
set board(40) "                x   x   x   x                                   "
set board(41) "                o   o   o   o                                   "
set board(42) "                 x   x   x   x                                  "
set board(43) "                 o   o   o   o                                  "
set board(44) "                  x   x   x   x                                 "
set board(45) "                  o   o   o   o                                 "
set board(46) "                   x   x   x   x                                "
set board(47) "                   o   o   o   o                                "
set board(48) "                                x   x   x   x                   "
set board(49) "                                o   o   o   o                   "
set board(50) "                                 x   x   x   x                  "
set board(51) "                                 o   o   o   o                  "
set board(52) "                                  x   x   x   x                 "
set board(53) "                                  o   o   o   o                 "
set board(54) "                                   x   x   x   x                "
set board(55) "                                   o   o   o   o                "
set board(56) "                                                x   x   x   x   "
set board(57) "                                                o   o   o   o   "
set board(58) "                                                 x   x   x   x  "
set board(59) "                                                 o   o   o   o  "
set board(60) "                                                  x   x   x   x "
set board(61) "                                                  o   o   o   o "
set board(62) "                                                   x   x   x   x"
set board(63) "                                                   o   o   o   o"
set board(64) "x               x               x               x               "
set board(65) "o               o               o               o               "
set board(66) " x               x               x               x              "
set board(67) " o               o               o               o              "
set board(68) "  x               x               x               x             "
set board(69) "  o               o               o               o             "
set board(70) "   x               x               x               x            "
set board(71) "   o               o               o               o            "
set board(72) "    x               x               x               x           "
set board(73) "    o               o               o               o           "
set board(74) "     x               x               x               x          "
set board(75) "     o               o               o               o          "
set board(76) "      x               x               x               x         "
set board(77) "      o               o               o               o         "
set board(78) "       x               x               x               x        "
set board(79) "       o               o               o               o        "
set board(80) "        x               x               x               x       "
set board(81) "        o               o               o               o       "
set board(82) "         x               x               x               x      "
set board(83) "         o               o               o               o      "
set board(84) "          x               x               x               x     "
set board(85) "          o               o               o               o     "
set board(86) "           x               x               x               x    "
set board(87) "           o               o               o               o    "
set board(88) "            x               x               x               x   "
set board(89) "            o               o               o               o   "
set board(90) "             x               x               x               x  "
set board(91) "             o               o               o               o  "
set board(92) "              x               x               x               x "
set board(93) "              o               o               o               o "
set board(94) "               x               x               x               x"
set board(95) "               o               o               o               o"
set board(96) "x    x    x    x                                                "
set board(97) "o    o    o    o                                                "
set board(98) "                x    x    x    x                                "
set board(99) "                o    o    o    o                                "
set board(100) "                                x    x    x    x                "
set board(101) "                                o    o    o    o                "
set board(102) "                                                x    x    x    x"
set board(103) "                                                o    o    o    o"
set board(104) "   x  x  x  x                                                   "
set board(105) "   o  o  o  o                                                   "
set board(106) "                   x  x  x  x                                   "
set board(107) "                   o  o  o  o                                   "
set board(108) "                                   x  x  x  x                   "
set board(109) "                                   o  o  o  o                   "
set board(110) "                                                   x  x  x  x   "
set board(111) "                                                   o  o  o  o   "
set board(112) "x                x                x                x            "
set board(113) "o                o                o                o            "
set board(114) "    x                x                x                x        "
set board(115) "    o                o                o                o        "
set board(116) "        x                x                x                x    "
set board(117) "        o                o                o                o    "
set board(118) "            x                x                x                x"
set board(119) "            o                o                o                o"
set board(120) "   x              x              x              x               "
set board(121) "   o              o              o              o               "
set board(122) "       x              x              x              x           "
set board(123) "       o              o              o              o           "
set board(124) "           x              x              x              x       "
set board(125) "           o              o              o              o       "
set board(126) "               x              x              x              x   "
set board(127) "               o              o              o              o   "
set board(128) "x                    x                    x                    x"
set board(129) "o                    o                    o                    o"
set board(130) "   x                  x                  x                  x   "
set board(131) "   o                  o                  o                  o   "
set board(132) "            x            x            x            x            "
set board(133) "            o            o            o            o            "
set board(134) "               x          x          x          x               "
set board(135) "               o          o          o          o               "
