set board(0) "xxxx    o o o o                                                 "
set board(1) "oooo    x x x x                                                 "
set board(2) "    xxxx   o o o o                                              "
set board(3) "    oooo   x x x x                                              "
set board(4) "                  ooo  o                         x   x   x   x  "
set board(5) "                  xxx  x                         o   o   o   o  "
set board(6) "                  o  o   o    o                   x   x   x   x "
set board(7) " x  o x     x    x  o               o               o           "
set board(8) "o    x            o  x    o          xo              x          "
set board(9) "x    o            x  o    x          ox              o          "
set board(10) "o oo o    x               x               x               x     "
set board(11) "x xx x          o    o    o    o                                "
set board(12) "oo o o                          x    x    x    x                "
set board(13) "xx x x                          o    o    o    o                "
set board(14) "oo  oo             x  x  x  x                                   "
set board(15) "xx  xx                                             o  o  o  o   "
set board(16) "x    o  o oo     x                x                x            "
set board(17) "o    x  x  xx    o                o                o            "
set board(18) "    x     ooo o      x                x                x        "
set board(19) "    o     xxx x      o                o                o        "
set board(20) "       x    oo o o    x              x              x           "
set board(21) "       o    xx x x    o              o              o           "
set board(22) "x     o oo o         x                    x                    x"
set board(23) "o     x xx x         o                    o                    o"
set board(24) "oo oo       x            x            x            x            "
set board(25) "xx xx       o            o            o            o            "
