#ifndef EFFECTS_H
#define EFFECTS_H

void restoreability(hero *mon);
void makeconfused(monstclass *mon);
void makeblind(monstclass *mon);
void makeparylized(monstclass *mon);
void makelevitate(monstclass *mon);
void makehallucinate(monstclass *mon);
void makeinvisible(monstclass *mon);
void seeinvisible(monstclass *mon);
void heal(monstclass *mon);
void extraheal(monstclass *mon);
void gainlevel(monstclass *mon);
void enchantarmor(monstclass *mon);
void destroyarmor(monstclass *mon);
void removecurse(monstclass *mon);
void enchantweapon(monstclass *mon);
void 


#endif
